backend:
  name: github
  repo: dominggo1999/netlify-cms
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://erfudia.vercel.app/
  auth_endpoint: api/auth
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - format: "json"
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - format: "json"
    name: "member"
    label: "Member"
    folder: "content/member"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string" 
      - label: "Role"
        name: "role"
        widget: "select"
        options:
          - { label: "Web Developer", value: "web-developer" }
          - { label: "Designer", value: "designer" }
          - { label: "Marketing", value: "marketing" } 
          - { label: "Staff", value: "staff" } 
      - label: "Profile Picture"
        name: "picture"
        widget: "image" 
  - format: "json"
    name : "faqs"
    label : "Faqs"
    folder : "content/faqs"
    create : true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label : "Question"
        name : "question"
        widget: "string"
      - label: "Answer"
        name : "answer"
        widget : "string"
           